# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_231856e4a6c4e856d1baa4fb0af6a099a6f7d86a

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client,controllers,models,routes,middlewares,helpers,config
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/backend/lcov.info,coverage/frontend/lcov.info,coverage/integration/lcov.info,coverage/frontend-integration/lcov.info

sonar.exclusions=node_modules/**,coverage/**,playwright-report/**,test-results/**,client/src/_site/**
sonar.coverage.exclusions=routes/**,server.js,testUtils/**,tests/helpers/**,__mocks__/**,client/src/setupTests.js,**/*.config.js,client/src/__tests__/**,client/src/index.js,client/src/App.js,client/src/reportWebVitals.js,client/public/mockServiceWorker.js,config/db.js