# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_f05f67a4ff82054575ace82bdd54d82848717830

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client,controllers
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/backend/lcov.info,coverage/frontend/lcov.info